source 'https://rubygems.org'

gem "cucumber-rest-api", "= 0.3"
gem 'minke', "= 1.13.16"
#gem 'minke', :path => '/Users/nicj/Developer/gems/minke'
gem 'minke-generator-swift', '= 0.5'# Update this to the name of your gem
#gem 'minke-generator-swift', :path => '/Users/nicj/Developer/gems/minke-generator-swift'
